# Generated by Django 5.1.3 on 2024-11-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'sos_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('loginId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('confirmPassword', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('address', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('mobileNumber', models.CharField(default='', max_length=50)),
                ('roleID', models.IntegerField()),
                ('roleName', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_user',
            },
        ),
    ]
