# Generated by Django 5.1.3 on 2024-11-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0002_rename_roleid_user_roleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roleName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
